# Quarkus port
quarkus.http.port=${PORT_SERVER:8082}
quarkus.vertx.event-loops-pool-size=4
quarkus.vertx.max-event-loop-execute-time=40000

# IBM MQ Configuration
ibm.mq.queueManager=QM1
ibm.mq.channel=DEV.APP.SVRCONN
#ibm.mq.connectionName=localhost(1414)
ibm.mq.connectionName=192.168.40.2(1414)
ibm.mq.applicationName=my-jms-app
ibm.mq.timeout=5000

# SmallRye Messaging JMS Configuration
mp.messaging.incoming.order.connector=smallrye-jms
mp.messaging.incoming.order.destination=DEV.QUEUE.1
mp.messaging.incoming.order.username=app
mp.messaging.incoming.order.password=app

# SmallRye Messaging JMS Configuration
mp.messaging.incoming.payment.connector=smallrye-jms
mp.messaging.incoming.payment.destination=DEV.QUEUE.2
mp.messaging.incoming.payment.username=app
mp.messaging.incoming.payment.password=app

# SmallRye Messaging JMS Configuration
mp.messaging.incoming.account-events.connector=smallrye-jms
mp.messaging.incoming.account-events.destination=DEV.QUEUE.3
mp.messaging.incoming.account-events.username=app
mp.messaging.incoming.account-events.password=app

quarkus.amqp.devservices.enabled=false

# Recursos de IBM MQ necesarios en imagen nativa
# META-INF/** cubre: compinfo.properties, ccsid_merged.map, IBM930*.dat, jmqiCharsets.dat, etc.
# com/ibm/mq/** cubre: ciphermappings.json y todos los message bundles .properties de IBM MQ
quarkus.native.resources.includes=META-INF/**,com/ibm/mq/**,com/ibm/msg/**

quarkus.native.additional-build-args=\
  --initialize-at-run-time=com.ibm.msg,\
  --initialize-at-run-time=com.ibm.mq,\
  --initialize-at-run-time=com.ibm.mq.jakarta,\
  --initialize-at-run-time=com.sun.jmx.mbeanserver.JmxMBeanServer,\
  --initialize-at-build-time=com.ibm.msg.client.jakarta.jms.JmsConstants
